# Generated by Django 3.1 on 2020-08-31 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200830_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
