# Generated by Django 3.1 on 2020-08-31 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='curent_username',
        ),
    ]
