# Generated by Django 3.1 on 2020-08-31 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200831_0118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='curent_username',
            new_name='user',
        ),
    ]
