# Generated by Django 3.1 on 2020-09-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
