# Generated by Django 3.1 on 2020-09-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_course_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='admin',
            new_name='admin_aprrover',
        ),
    ]
