# Generated by Django 3.1 on 2020-09-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200902_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='errol',
            new_name='link_to_course',
        ),
    ]
