# Generated by Django 3.1 on 2020-09-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200902_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='admin_aprrover',
            new_name='admin_approver',
        ),
    ]
