# Generated by Django 3.1 on 2020-09-03 18:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200903_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 18, 24, 7, 34571, tzinfo=utc)),
        ),
    ]
