# Generated by Django 3.1 on 2020-09-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200903_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['date']},
        ),
    ]
